repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: (^frontend/|^backend/|^.idea/|^deploy/)
      - id: end-of-file-fixer
        exclude: (^frontend/|^backend/|^.idea/|^deploy/|^\.nvmrc|^\.gitlab-ci.yml)
      - id: check-yaml
        exclude: ^deploy/
      - id: check-added-large-files
      - id: check-toml
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/psf/black
    # black config is in pyproject.toml
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        language_version: python3
        args: [--profile=black, --line-length=120]
  - repo: https://github.com/PyCQA/flake8
    # flake8 config is in .flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.991'  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        exclude: "[a-zA-Z]*/(migrations)/(.)*"
        args: [--no-strict-optional,
               --ignore-missing-imports]
